# Generated by Django 3.2.23 on 2023-11-21 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='scanned_quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='scannedproducts',
            name='cashier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scannedproducts',
            name='summed_product_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scannedproducts',
            name='product',
            field=models.ManyToManyField(blank=True, to='management.Product'),
        ),
    ]
