# Generated by Django 3.2.23 on 2023-11-22 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_cashierdynamicproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scannedproducts',
            name='product',
            field=models.ManyToManyField(blank=True, to='management.CashierDynamicProducts'),
        ),
    ]
