# Generated by Django 3.2.23 on 2023-12-05 06:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_scannedproductheader'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldproducts',
            name='date_sold_no_time',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
