# Generated by Django 3.2.23 on 2023-12-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_soldproducts_date_sold_no_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoldOutProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('barcode', models.CharField(max_length=255)),
                ('date_sold_out', models.DateField(auto_now_add=True)),
                ('date_sold_out_time', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
