# Generated by Django 3.2.23 on 2023-12-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_cashierdynamicproducts_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=400)),
                ('is_seen', models.BooleanField(blank=True, default=False, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
