# Generated by Django 3.2.23 on 2023-12-22 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-date_time']},
        ),
        migrations.AddField(
            model_name='notification',
            name='removed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
