# Generated by Django 3.2.23 on 2023-12-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_auto_20231222_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='identifier',
            field=models.CharField(default='yeah', max_length=500),
            preserve_default=False,
        ),
    ]
