# Generated by Django 3.2.23 on 2024-01-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_auto_20240105_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldproduct',
            name='date_sold',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='soldproduct',
            name='date_sold_no_time',
            field=models.DateField(null=True),
        ),
    ]
