# Generated by Django 3.2.23 on 2024-01-06 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_auto_20240105_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='scannedproductheader',
            name='change',
            field=models.IntegerField(null=True),
        ),
    ]
