# Generated by Django 3.2.23 on 2024-01-16 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0018_scannedproductheader_change'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('date_no_time', models.DateField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='TotalExpenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense', models.IntegerField(default=0)),
            ],
        ),
    ]
