# Generated by Django 3.2.23 on 2024-01-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0019_expenses_totalexpenses'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.IntegerField(default=0)),
            ],
        ),
    ]
