# Generated by Django 3.2.23 on 2024-01-17 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0020_totalincome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue', models.IntegerField(default=0)),
                ('date', models.DateField(blank=True, null=True)),
                ('date_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TotalRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue', models.IntegerField(default=0)),
                ('last_updated', models.DateField(blank=True, null=True)),
                ('last_updated_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='totalexpenses',
            name='last_updated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='totalexpenses',
            name='last_updated_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='totalincome',
            name='last_updated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='totalincome',
            name='last_updated_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
