# Generated by Django 3.2.23 on 2024-01-17 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0021_auto_20240117_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='date_no_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
