# Generated by Django 3.2.23 on 2024-01-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0022_auto_20240117_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('date_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Income',
                'ordering': ['-date'],
            },
        ),
        migrations.AlterModelOptions(
            name='revenue',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Revenues'},
        ),
    ]
